import {
  REMOTE_FEED_URL as CONFIG_REMOTE_FEED_URL,
  REMOTE_FEED_BASELINE_URL as CONFIG_REMOTE_FEED_BASELINE_URL,
  REMOTE_FEED_USER_URL as CONFIG_REMOTE_FEED_USER_URL,
} from "./env";

export const REMOTE_FEED_URL = CONFIG_REMOTE_FEED_URL;
export const REMOTE_FEED_BASELINE_URL = CONFIG_REMOTE_FEED_BASELINE_URL;
export const REMOTE_FEED_USER_URL = CONFIG_REMOTE_FEED_USER_URL;

